---
all:
  hosts:
    psql_1:
      ansible_host: 192.168.100.71
      ansible_user: goblin
      #ansible_become_password: sinpgamjppli

  children:
    grafana:
      hosts: psql_1

    prometheus:
      hosts: psql_1

    node_exporter:
      hosts: psql_1

    install_prometheus_postgres_exporter:
      hosts: psql_1

    postgresql:
      hosts: psql_1
